version: '3'

volumes:
  pg_data:

services:
  db:
    image: postgres
    restart: always
    env_file: bot/.env
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: bot
    volumes:
      - pg_data:/var/lib/postgresql/dat
  backend:
    image: flyoverthesky/wb_tg_bot:latest
    restart: always
    env_file: bot/.env
    depends_on:
      - db